title: Fallout Shelter Wiki
description: Collection of Fallout Shelter Information
exclude: [
  '_pagebuilder/',
  '.idea/**',
]
theme: jekyll-theme-cayman
gems:
  - jekyll-mentions
plugins:
  - jekyll-relative-links
